### ISSUE TITLE
FQL deprecated

### ISSUE THREAD

**Issue by andresfunes** [restfb/restfb-examples#3]
I run the first example and i get:
Facebook responded with HTTP status code 400 and response body: {"error":{"message":"(#12) fql is deprecated for versions v2.1 and higher","type":"OAuthException","code":12,"fbtrace_id":"F+aASIBicmw"}}

Exception is from:
List<JsonObject> queryResults = facebookClient20.executeFqlQuery(query, JsonObject.class);

Why told me that i use version v2.1 if facebookClient20 has Version.VERSION_2_0?
facebookClient20 = new DefaultFacebookClient(accessToken, Version.VERSION_2_0);

**Comment by nbartels** [comment]
Because your Facebook app has a higher minimum version. You can find this version in the App Dashboard. The minimum version is used to make the calls even if you define a older version. That's how Facebook handles the versioning ...

Nevertheless we should remove these examples, because FQL is discontinued and deprecated since April 2016 ;)
